name: pusher_flutter
description: A flutter plugin for Pusher (pusher.com)
version: 0.0.7
author: Matthew Smith <matthew@apptree.cloud>
homepage: https://github.com/apptreesoftware/pusher_flutter

environment:
  sdk: ">=2.0.0 <3.0.0"

flutter:
  plugin:
    androidPackage: com.apptreesoftware.pusherflutter
    pluginClass: PusherFlutterPlugin

dependencies:
  flutter:
    sdk: flutter
